# Generated by Django 4.2.11 on 2024-04-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Service",),
    ]
